apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-migrate
  namespace: airflow
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: install-requirements
          image: apache/airflow:3.2.2-python3.11
          command:
            - /bin/bash
            - -c
            - pip install --no-cache-dir --user -r /requirements/requirements.txt
          volumeMounts:
            - mountPath: /requirements
              name: requirements-volume
            - mountPath: /home/airflow/.local
              name: airflow-user-site
      containers:
        - name: migrate
          image: apache/airflow:3.2.2-python3.11
          command:
            - airflow
            - db
            - migrate
          env:
            - name: AIRFLOW_HOME
              value: /home/airflow
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /home/airflow/dags
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secret
                  key: DATABASE_URL
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
          volumeMounts:
            - mountPath: /home/airflow
              name: airflow-home
            - mountPath: /home/airflow/.local
              name: airflow-user-site
      volumes:
        - name: airflow-home
          emptyDir: {}
        - name: airflow-user-site
          emptyDir: {}
        - name: requirements-volume
          configMap:
            name: airflow-requirements
