apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-migrate
  namespace: airflow
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: install-requirements
          image: apache/airflow:3.2.2-python3.11
          command:
            - /bin/bash
            - -c
            - pip install --no-cache-dir --user -r /requirements/requirements.txt
          volumeMounts:
            - mountPath: /requirements
              name: requirements-volume
            - mountPath: /home/airflow/.local
              name: airflow-user-site
      containers:
        - name: migrate
          image: apache/airflow:3.2.2-python3.11
          # Gewijzigd naar bash om zowel de migratie als de admin user aan te maken
          command:
            - /bin/bash
            - -c
            - |
              echo "Running database migrations..."
              airflow db migrate

              echo "Creating admin user from GitHub Secrets..."
              airflow users create \
                --username "$NEW_ADMIN_USER" \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@nandersorg.local \
                --password "$NEW_ADMIN_PASS" || echo "User might already exist."
          env:
            - name: AIRFLOW_HOME
              value: /home/airflow
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /home/airflow/dags
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secret
                  key: DATABASE_URL
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            # Inladen van de admin secrets uit de nieuwe secret naam van deploy.yaml
            - name: NEW_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-admin-secret
                  key: USERNAME
            - name: NEW_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-admin-secret
                  key: PASSWORD
            - name: _AIRFLOW_DB_MIGRATION
              value: "true"
            - name: AIRFLOW__CORE__AUTH_MANAGER
              value: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
            - name: AIRFLOW__FAB__AUTH_TYPE
              value: "database"
          volumeMounts:
            - mountPath: /home/airflow
              name: airflow-home
            - mountPath: /home/airflow/.local
              name: airflow-user-site
      volumes:
        - name: airflow-home
          emptyDir: {}
        - name: airflow-user-site
          emptyDir: {}
        - name: requirements-volume
          configMap:
            name: airflow-requirements
